BuffParam={}
require "game/buff/LBornBuff"
require "game/buff/LDieBuff"
require "game/buff/LChenMo"
require "game/buff/LDingShen"
require "game/buff/LHuiXue"
require "game/buff/LJianSu"
require "game/buff/LJianXue"
require "game/buff/LJinGang"
require "game/buff/LJingHua"
require "game/buff/LJinGu"
require "game/buff/LSkillHarm"
require "game/buff/LLeiGongBaoFeng"